예제1) 불순도 측정

In [ ]:
import numpy as np
import math

p_T = np.array([3/9, 4/9, 2/9])

im_of_entropy = 0
im_of_gini = 1
for i in p_T:
  im_of_entropy += - i*math.log2(i)
  im_of_gini += - i ** 2

im_of_miss = 1 - max(p_T)

print(im_of_entropy)
print(im_of_gini)
print(im_of_miss)

1.5304930567574824
0.6419753086419753
0.5555555555555556


예제3) 불순도 감소량

In [ ]:
import numpy as np
import math

sample = np.array([[3, 1, 50.6, 2], [2, 3, 72.8, 1], [3, 5, 88.7, 3], [2, 2, 102.2, 2], [5, 5, 92.3, 2], [3, 4, 65.3, 2], [2, 3, 67.8, 1], [7, 1, 47.8, 3], [2, 3, 45.6, 1]])
N_X_T = sample.shape[0]

print(sample, '\n')

# question x1 == ?
q_x1 = np.arange(7)+1;
print(q_x1)

for j in q_x1:
  N_X_left = sum(sample.T[0] == j)
  N_X_right = sum(sample.T[0] != j)

  sample_left = sample[sample.T[0] == j]
  N_X_left_T = sample_left.shape[0]
  sample_left_w = sample_left[:,3]
#   print(j,':',sample_left,'\n')
#   print(j,':',N_X_left_T,'\n')
#   print(j,':',sample_left_w,'\n')
  if N_X_left_T != 0:
    p_T_left = np.array([sum(sample_left_w==1), sum(sample_left_w==2), sum(sample_left_w==3)])/N_X_left_T
  else:
    p_T_left = np.zeros(3)

  im_of_gini_left = 1
  for i in p_T_left:
    im_of_gini_left += - i ** 2

  sample_right = sample[sample.T[0] != j]
  N_X_right_T = sample_right.shape[0]
  sample_right_w = sample_right[:,3]
  if N_X_right_T != 0:
    p_T_right = np.array([sum(sample_right_w==1), sum(sample_right_w==2), sum(sample_right_w==3)])/N_X_right_T
  else:
    p_T_right = np.zeros(3)

  im_of_gini_right = 1
  for i in p_T_right:
    im_of_gini_right += - i ** 2

  print(im_of_gini_left, im_of_gini_right)

  delta_im_x1 = im_of_gini - N_X_left/N_X_T*im_of_gini_left - N_X_right/N_X_T*im_of_gini_right
  print(f'x1=={j}? : {delta_im_x1}')



[[  3.    1.   50.6   2. ]
 [  2.    3.   72.8   1. ]
 [  3.    5.   88.7   3. ]
 [  2.    2.  102.2   2. ]
 [  5.    5.   92.3   2. ]
 [  3.    4.   65.3   2. ]
 [  2.    3.   67.8   1. ]
 [  7.    1.   47.8   3. ]
 [  2.    3.   45.6   1. ]] 

[1 2 3 4 5 6 7]
1.0 0.6419753086419753
x1==1? : 0.0
0.375 0.48
x1==2? : 0.20864197530864198
0.4444444444444445 0.611111111111111
x1==3? : 0.0864197530864198
1.0 0.6419753086419753
x1==4? : 0.0
0.0 0.65625
x1==5? : 0.058641975308642014
1.0 0.6419753086419753
x1==6? : 0.0
0.0 0.59375
x1==7? : 0.11419753086419748


특징벡터 x2 기반 질문

In [ ]:
# question x2 == ?
q_x2 = np.arange(5)+1;
print(q_x2)

for j in q_x2:
  N_X_left = sum(sample.T[1] == j)
  N_X_right = sum(sample.T[1] != j)

  sample_left = sample[sample.T[1] == j]
  N_X_left_T = sample_left.shape[0]
  sample_left_w = sample_left[:,3]
  if N_X_left_T != 0:
    p_T_left = np.array([sum(sample_left_w==1), sum(sample_left_w==2), sum(sample_left_w==3)])/N_X_left_T
  else:
    p_T_left = np.zeros(3)

  im_of_gini_left = 1
  for i in p_T_left:
    im_of_gini_left += - i ** 2

  sample_right = sample[sample.T[1] != j]
  N_X_right_T = sample_right.shape[0]
  sample_right_w = sample_right[:,3]
  if N_X_right_T != 0:
    p_T_right = np.array([sum(sample_right_w==1), sum(sample_right_w==2), sum(sample_right_w==3)])/N_X_right_T
  else:
    p_T_right = np.zeros(3)

  im_of_gini_right = 1
  for i in p_T_right:
    im_of_gini_right += - i ** 2

#  print(im_of_gini_left, im_of_gini_right)

  delta_im_x2 = im_of_gini - N_X_left/N_X_T*im_of_gini_left - N_X_right/N_X_T*im_of_gini_right
  print(f'x2=={j}? : {delta_im_x2}')

[1 2 3 4 5]
0.5 0.6122448979591837
x2==1? : 0.05467372134038789
0.0 0.65625
x2==2? : 0.058641975308642014
0.0 0.4444444444444445
x2==3? : 0.345679012345679
0.0 0.65625
x2==4? : 0.058641975308642014
0.5 0.6122448979591837
x2==5? : 0.05467372134038789


특징벡터 x3 기반 질문

In [ ]:
# question x3 < ?
q_x3 = np.array([46.7, 49.2, 57.95, 66.55, 70.3, 80.75, 90.5, 97.25])
print(q_x3)

for j in q_x3:
  N_X_left = sum(sample.T[2] < j)
  N_X_right = sum(sample.T[2] >= j)

  sample_left = sample[sample.T[2] < j]
  N_X_left_T = sample_left.shape[0]
  sample_left_w = sample_left[:,3]
  if N_X_left_T != 0:
    p_T_left = np.array([sum(sample_left_w==1), sum(sample_left_w==2), sum(sample_left_w==3)])/N_X_left_T
  else:
    p_T_left = np.zeros(3)

  im_of_gini_left = 1
  for i in p_T_left:
    im_of_gini_left += - i ** 2

  sample_right = sample[sample.T[2] >= j]
  N_X_right_T = sample_right.shape[0]
  sample_right_w = sample_right[:,3]
  if N_X_right_T != 0:
    p_T_right = np.array([sum(sample_right_w==1), sum(sample_right_w==2), sum(sample_right_w==3)])/N_X_right_T
  else:
    p_T_right = np.zeros(3)

  im_of_gini_right = 1
  for i in p_T_right:
    im_of_gini_right += - i ** 2

  delta_im_x3 = im_of_gini - N_X_left/N_X_T*im_of_gini_left - N_X_right/N_X_T*im_of_gini_right
  print(f'x3<{j} ? : {delta_im_x3}')

[46.7  49.2  57.95 66.55 70.3  80.75 90.5  97.25]
x3<46.7? : 0.08641975308641969
x3<49.2? : 0.08641975308641969
x3<57.95? : 0.01234567901234579
x3<66.55? : 0.00864197530864197
x3<70.3? : 0.00864197530864197
x3<80.75? : 0.0864197530864198
x3<90.5? : 0.13403880070546725
x3<97.25? : 0.058641975308642014
